### ISSUE TITLE
Replace include country-code a flag logic w/ default '+45'

### ISSUE THREAD

**Issue by holgerthorup** [covid19-group/c19#10]
While this solution is only locally implemented and we have a hard constraint w/ Twilio on only sending to Danish numbers (+45) there is no need to have every single user write +45 in the input field.

We should just prefix it to their number if they didn't write and maybe even make it a visible prefix (replacing the current flag).

But let's keep the current functionality for future/international expansion.

**Comment by louislva** [comment]
I've implemented this.
