### ISSUE TITLE
Set up SMS sending w/ Sinch

### ISSUE THREAD

**Issue by holgerthorup** [covid19-group/c19#8]
We're expecting a go from Danish teleproviders to switch to their network for a more reasonable deal that Twilio. They have an integration set up with another provider and believe it's easier for us to integrate through them than directly to the teleproviders. 

Setup using a trial account for now: https://www.sinch.com/products/messaging/sms/

Let's keep the integration to Twilio – to enable other countries to use that service (also it works, so why not) :D

**Comment by louislva** [comment]
I've created an integration, but not put it in use anywhere, as we don't have an org account/any credits. Not closing the issue yet.

**Comment by louislva** [comment]
Note on this: they said they might have a phone number ready for us later today or Monday. We're hoping 🤞

**Comment by louislva** [comment]
We have phone no, and the integration is ready for use - we just need fees waived. Closing issue.
